In [1]:
import os, math, json
import numpy as np
from matplotlib import pyplot as plt
from keras import applications
from keras.preprocessing.image import ImageDataGenerator
from keras import optimizers
from keras.models import Sequential, Model, model_from_json
from keras.layers import Dropout, Flatten, Dense, GlobalAveragePooling2D
from keras import backend as k 
from keras.callbacks import ModelCheckpoint, LearningRateScheduler, TensorBoard
from keras.applications import VGG16, InceptionV3
from keras import metrics, losses
from sklearn.metrics import roc_curve, auc, roc_auc_score, accuracy_score, classification_report, confusion_matrix 

/data/anaconda/envs/py35/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
# Varibles and parametes used in the model
classes = [0, 1]
num_classes = 2
batch_size = 64
epochs = 10 
steps_per_epochs = 300
learning_rate = 0.0001
metric = ["accuracy"]
loss = "binary_crossentropy"

In [3]:
train_path = '/home/sofus/deep/data/train/'
test_path = '/home/sofus/deep/data/test/'
val_path = '/home/sofus/deep/data/val/'

test_datagen = ImageDataGenerator()

In [4]:
# load json and create model
json_file = open('vgg16_ep10.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("vgg16_ep.h5")
print("Loaded model from disk")

loaded_model.compile(loss = loss,
        optimizer = optimizers.SGD(lr=learning_rate, momentum=0.9),
        metrics=metric)

Instructions for updating:
Colocations handled automatically by placer.
Loaded model from disk


## Test test

In [9]:
test_generator = test_datagen.flow_from_directory(
        '/home/sofus/deep/data/test',
        batch_size=batch_size,
        shuffle=False,
        class_mode='categorical')

print("[INFO] evaluating network...")
test_generator.reset()
predIdxs = loaded_model.predict_generator(test_generator, steps=(test_generator.classes.size/batch_size))

# for each image in the testing set we need to find the index of the
# label with corresponding largest predicted probability
predIdxs1 = np.argmax(predIdxs, axis=1)

Found 7998 images belonging to 2 classes.
[INFO] evaluating network...


In [10]:
confusion_matrix(test_generator.classes, predIdxs1)

array([[3999,    0],
       [  12, 3987]])

In [11]:
accuracy_score(test_generator.classes, predIdxs1)

0.9984996249062266

## Gaussian noise with a variance of 5

In [6]:
test_generator = test_datagen.flow_from_directory(
        '/home/sofus/deep/data/Augmented/gauss/5',
        batch_size=batch_size,
        shuffle=False,
        class_mode='categorical')

Found 7998 images belonging to 2 classes.


In [7]:
print("[INFO] evaluating network...")
test_generator.reset()
predIdxs = loaded_model.predict_generator(test_generator, steps=(test_generator.classes.size/batch_size))

# for each image in the testing set we need to find the index of the
# label with corresponding largest predicted probability
predIdxs = np.argmax(predIdxs, axis=1)

[INFO] evaluating network...


In [8]:
confusion_matrix(test_generator.classes, predIdxs)

array([[3997,    2],
       [  14, 3985]])

In [9]:
accuracy_score(test_generator.classes, predIdxs)

0.9979994998749687

## Gauss 10

In [10]:
test_generator = test_datagen.flow_from_directory(
        '/home/sofus/deep/data/Augmented/gauss/10',
        batch_size=batch_size,
        shuffle=False,
        class_mode='categorical')

Found 7998 images belonging to 2 classes.


In [11]:
print("[INFO] evaluating network...")
test_generator.reset()
predIdxs = loaded_model.predict_generator(test_generator, steps=(test_generator.classes.size/batch_size))

# for each image in the testing set we need to find the index of the
# label with corresponding largest predicted probability
predIdxs = np.argmax(predIdxs, axis=1)

[INFO] evaluating network...


In [12]:
confusion_matrix(test_generator.classes, predIdxs)

array([[3989,   10],
       [  12, 3987]])

In [13]:
accuracy_score(test_generator.classes, predIdxs)

0.997249312328082

## Gauss 30

In [14]:
test_generator = test_datagen.flow_from_directory(
        '/home/sofus/deep/data/Augmented/gauss/30',
        batch_size=batch_size,
        shuffle=False,
        class_mode='categorical')

Found 7998 images belonging to 2 classes.


In [15]:
print("[INFO] evaluating network...")
test_generator.reset()
predIdxs = loaded_model.predict_generator(test_generator, steps=(test_generator.classes.size/batch_size))

# for each image in the testing set we need to find the index of the
# label with corresponding largest predicted probability
predIdxs = np.argmax(predIdxs, axis=1)

[INFO] evaluating network...


In [16]:
confusion_matrix(test_generator.classes, predIdxs)

array([[3998,    1],
       [ 578, 3421]])

In [17]:
accuracy_score(test_generator.classes, predIdxs)

0.9276069017254314

## Gauss 20

In [5]:
test_generator = test_datagen.flow_from_directory(
        '/home/sofus/deep/data/Augmented/gauss/20',
        batch_size=batch_size,
        shuffle=False,
        class_mode='categorical')

print("[INFO] evaluating network...")
test_generator.reset()
predIdxs = loaded_model.predict_generator(test_generator, steps=(test_generator.classes.size/batch_size))

# for each image in the testing set we need to find the index of the
# label with corresponding largest predicted probability
predIdxs = np.argmax(predIdxs, axis=1)

Found 7998 images belonging to 2 classes.
[INFO] evaluating network...


In [6]:
confusion_matrix(test_generator.classes, predIdxs)

array([[3997,    2],
       [  54, 3945]])

In [7]:
accuracy_score(test_generator.classes, predIdxs)

0.9929982495623906

## Gauss 15

In [8]:
test_generator = test_datagen.flow_from_directory(
        '/home/sofus/deep/data/Augmented/gauss/15',
        batch_size=batch_size,
        shuffle=False,
        class_mode='categorical')

print("[INFO] evaluating network...")
test_generator.reset()
predIdxs = loaded_model.predict_generator(test_generator, steps=(test_generator.classes.size/batch_size))

# for each image in the testing set we need to find the index of the
# label with corresponding largest predicted probability
predIdxs = np.argmax(predIdxs, axis=1)

Found 7998 images belonging to 2 classes.
[INFO] evaluating network...


In [9]:
confusion_matrix(test_generator.classes, predIdxs)

array([[3990,    9],
       [  12, 3987]])

In [10]:
accuracy_score(test_generator.classes, predIdxs)

0.9973743435858965

## Darkenededed with 0.1

In [78]:
test_generator = test_datagen.flow_from_directory(
        '/home/sofus/deep/data/Augmented/darken/dark01',
        batch_size=batch_size,
        shuffle=False,
        class_mode='categorical')

print("[INFO] evaluating network...")
test_generator.reset()
predIdxs = loaded_model.predict_generator(test_generator, steps=(test_generator.classes.size/batch_size))

# for each image in the testing set we need to find the index of the
# label with corresponding largest predicted probability
predIdxs = np.argmax(predIdxs, axis=1)

Found 7998 images belonging to 2 classes.
[INFO] evaluating network...


In [79]:
confusion_matrix(test_generator.classes, predIdxs)

array([[3999,    0],
       [  48, 3951]])

In [80]:
accuracy_score(test_generator.classes, predIdxs)

0.9939984996249063

## Darkenedended with 0.5

In [81]:
test_generator = test_datagen.flow_from_directory(
        '/home/sofus/deep/data/Augmented/darken/dark05',
        batch_size=batch_size,
        shuffle=False,
        class_mode='categorical')

print("[INFO] evaluating network...")
test_generator.reset()
predIdxs = loaded_model.predict_generator(test_generator, steps=(test_generator.classes.size/batch_size))

# for each image in the testing set we need to find the index of the
# label with corresponding largest predicted probability
predIdxs = np.argmax(predIdxs, axis=1)

Found 7998 images belonging to 2 classes.
[INFO] evaluating network...


In [82]:
confusion_matrix(test_generator.classes, predIdxs)

array([[3999,    0],
       [  13, 3986]])

In [83]:
accuracy_score(test_generator.classes, predIdxs)

0.9983745936484121

## Darkend with 1.7

In [87]:
test_generator = test_datagen.flow_from_directory(
        '/home/sofus/deep/data/Augmented/darken/dark17',
        batch_size=batch_size,
        shuffle=False,
        class_mode='categorical')

print("[INFO] evaluating network...")
test_generator.reset()
predIdxs = loaded_model.predict_generator(test_generator, steps=(test_generator.classes.size/batch_size))

# for each image in the testing set we need to find the index of the
# label with corresponding largest predicted probability
predIdxs = np.argmax(predIdxs, axis=1)

Found 7998 images belonging to 2 classes.
[INFO] evaluating network...


In [88]:
confusion_matrix(test_generator.classes, predIdxs)

array([[3999,    0],
       [  54, 3945]])

In [89]:
accuracy_score(test_generator.classes, predIdxs)

0.9932483120780196

## Darkend with 25

In [90]:
test_generator = test_datagen.flow_from_directory(
        '/home/sofus/deep/data/Augmented/darken/dark25',
        batch_size=batch_size,
        shuffle=False,
        class_mode='categorical')

print("[INFO] evaluating network...")
test_generator.reset()
predIdxs = loaded_model.predict_generator(test_generator, steps=(test_generator.classes.size/batch_size))

# for each image in the testing set we need to find the index of the
# label with corresponding largest predicted probability
predIdxs = np.argmax(predIdxs, axis=1)

Found 7998 images belonging to 2 classes.
[INFO] evaluating network...


In [91]:
confusion_matrix(test_generator.classes, predIdxs)

array([[3999,    0],
       [ 487, 3512]])

In [92]:
accuracy_score(test_generator.classes, predIdxs)

0.9391097774443611

## Darken  with 3

In [93]:
test_generator = test_datagen.flow_from_directory(
        '/home/sofus/deep/data/Augmented/darken/dark30',
        batch_size=batch_size,
        shuffle=False,
        class_mode='categorical')

print("[INFO] evaluating network...")
test_generator.reset()
predIdxs = loaded_model.predict_generator(test_generator, steps=(test_generator.classes.size/batch_size))

# for each image in the testing set we need to find the index of the
# label with corresponding largest predicted probability
predIdxs = np.argmax(predIdxs, axis=1)

Found 7998 images belonging to 2 classes.
[INFO] evaluating network...


In [94]:
confusion_matrix(test_generator.classes, predIdxs)

array([[3999,    0],
       [ 951, 3048]])

In [95]:
accuracy_score(test_generator.classes, predIdxs)

0.8810952738184546

## Darken 0.05

In [96]:
test_generator = test_datagen.flow_from_directory(
        '/home/sofus/deep/data/Augmented/darken/dark005',
        batch_size=batch_size,
        shuffle=False,
        class_mode='categorical')

print("[INFO] evaluating network...")
test_generator.reset()
predIdxs = loaded_model.predict_generator(test_generator, steps=(test_generator.classes.size/batch_size))

# for each image in the testing set we need to find the index of the
# label with corresponding largest predicted probability
predIdxs = np.argmax(predIdxs, axis=1)

Found 7998 images belonging to 2 classes.
[INFO] evaluating network...


In [97]:
confusion_matrix(test_generator.classes, predIdxs)

array([[3998,    1],
       [ 498, 3501]])

In [98]:
accuracy_score(test_generator.classes, predIdxs)

0.9376094023505877

## Saltpepper 0.3

In [99]:
test_generator = test_datagen.flow_from_directory(
        '/home/sofus/deep/data/Augmented/Saltnpepper/salt03',
        batch_size=batch_size,
        shuffle=False,
        class_mode='categorical')

print("[INFO] evaluating network...")
test_generator.reset()
predIdxs = loaded_model.predict_generator(test_generator, steps=(test_generator.classes.size/batch_size))

# for each image in the testing set we need to find the index of the
# label with corresponding largest predicted probability
predIdxs = np.argmax(predIdxs, axis=1)

Found 7998 images belonging to 2 classes.
[INFO] evaluating network...


In [100]:
confusion_matrix(test_generator.classes, predIdxs)

array([[3603,  396],
       [  17, 3982]])

In [101]:
accuracy_score(test_generator.classes, predIdxs)

0.9483620905226307

## Saltpepper 0.03

In [17]:
test_generator = test_datagen.flow_from_directory(
        '/home/sofus/deep/data/Augmented/Saltnpepper/salt003',
        batch_size=batch_size,
        shuffle=False,
        class_mode='categorical')

print("[INFO] evaluating network...")
test_generator.reset()
predIdxs = loaded_model.predict_generator(test_generator, steps=(test_generator.classes.size/batch_size))

# for each image in the testing set we need to find the index of the
# label with corresponding largest predicted probability
predIdxs = np.argmax(predIdxs, axis=1)

Found 7998 images belonging to 2 classes.
[INFO] evaluating network...


In [18]:
confusion_matrix(test_generator.classes, predIdxs)

array([[3999,    0],
       [ 205, 3794]])

In [19]:
accuracy_score(test_generator.classes, predIdxs)

0.9743685921480371

## Saltpepper 0.05

In [11]:
test_generator = test_datagen.flow_from_directory(
        '/home/sofus/deep/data/Augmented/Saltnpepper/salt005',
        batch_size=batch_size,
        shuffle=False,
        class_mode='categorical')

print("[INFO] evaluating network...")
test_generator.reset()
predIdxs = loaded_model.predict_generator(test_generator, steps=(test_generator.classes.size/batch_size))

# for each image in the testing set we need to find the index of the
# label with corresponding largest predicted probability
predIdxs = np.argmax(predIdxs, axis=1)

Found 7998 images belonging to 2 classes.
[INFO] evaluating network...


In [12]:
confusion_matrix(test_generator.classes, predIdxs)

array([[3998,    1],
       [ 178, 3821]])

In [13]:
accuracy_score(test_generator.classes, predIdxs)

0.9776194048512128

## Saltpepper 0.1

In [18]:
test_generator = test_datagen.flow_from_directory(
        '/home/sofus/deep/data/Augmented/Saltnpepper/salt01',
        batch_size=batch_size,
        shuffle=False,
        class_mode='categorical')

print("[INFO] evaluating network...")
test_generator.reset()
predIdxs = loaded_model.predict_generator(test_generator, steps=(test_generator.classes.size/batch_size))

# for each image in the testing set we need to find the index of the
# label with corresponding largest predicted probability
predIdxs = np.argmax(predIdxs, axis=1)

Found 7998 images belonging to 2 classes.
[INFO] evaluating network...


In [19]:
confusion_matrix(test_generator.classes, predIdxs)

array([[3999,    0],
       [ 191, 3808]])

In [20]:
accuracy_score(test_generator.classes, predIdxs)

0.9761190297574394

## Saltpepper 0.2

In [21]:
test_generator = test_datagen.flow_from_directory(
        '/home/sofus/deep/data/Augmented/Saltnpepper/salt02',
        batch_size=batch_size,
        shuffle=False,
        class_mode='categorical')

print("[INFO] evaluating network...")
test_generator.reset()
predIdxs = loaded_model.predict_generator(test_generator, steps=(test_generator.classes.size/batch_size))

# for each image in the testing set we need to find the index of the
# label with corresponding largest predicted probability
predIdxs = np.argmax(predIdxs, axis=1)

Found 7998 images belonging to 2 classes.
[INFO] evaluating network...


In [22]:
confusion_matrix(test_generator.classes, predIdxs)

array([[3998,    1],
       [ 288, 3711]])

In [23]:
accuracy_score(test_generator.classes, predIdxs)

0.9638659664916229

## Saltpepper 0.05

In [14]:
test_generator = test_datagen.flow_from_directory(
        '/home/sofus/deep/data/Augmented/Saltnpepper/salt005',
        batch_size=batch_size,
        shuffle=False,
        class_mode='categorical')

print("[INFO] evaluating network...")
test_generator.reset()
predIdxs = loaded_model.predict_generator(test_generator, steps=(test_generator.classes.size/batch_size))

# for each image in the testing set we need to find the index of the
# label with corresponding largest predicted probability
predIdxs = np.argmax(predIdxs, axis=1)

Found 7998 images belonging to 2 classes.
[INFO] evaluating network...


In [15]:
confusion_matrix(test_generator.classes, predIdxs)

array([[3998,    1],
       [ 178, 3821]])

In [16]:
accuracy_score(test_generator.classes, predIdxs)

0.9776194048512128

## Saltpepper 1.1

In [69]:
test_generator = test_datagen.flow_from_directory(
        '/home/sofus/deep/data/Augmented/Saltnpepper/salt11',
        batch_size=batch_size,
        shuffle=False,
        class_mode='categorical')

print("[INFO] evaluating network...")
test_generator.reset()
predIdxs = loaded_model.predict_generator(test_generator, steps=(test_generator.classes.size/batch_size))

# for each image in the testing set we need to find the index of the
# label with corresponding largest predicted probability
predIdxs = np.argmax(predIdxs, axis=1)

Found 1200 images belonging to 2 classes.
[INFO] evaluating network...


In [70]:
confusion_matrix(test_generator.classes, predIdxs)

array([[594,   6],
       [ 35, 565]])

In [71]:
accuracy_score(test_generator.classes, predIdxs)

0.9658333333333333

## Saltpepper 1.3

In [72]:
test_generator = test_datagen.flow_from_directory(
        '/home/sofus/deep/data/Augmented/Saltnpepper/salt13',
        batch_size=batch_size,
        shuffle=False,
        class_mode='categorical')

print("[INFO] evaluating network...")
test_generator.reset()
predIdxs = loaded_model.predict_generator(test_generator, steps=(test_generator.classes.size/batch_size))

# for each image in the testing set we need to find the index of the
# label with corresponding largest predicted probability
predIdxs = np.argmax(predIdxs, axis=1)

Found 1200 images belonging to 2 classes.
[INFO] evaluating network...


In [73]:
confusion_matrix(test_generator.classes, predIdxs)

array([[597,   3],
       [ 57, 543]])

In [74]:
accuracy_score(test_generator.classes, predIdxs)

0.95

## Saltpepper 2

In [75]:
test_generator = test_datagen.flow_from_directory(
        '/home/sofus/deep/data/Augmented/Saltnpepper/salt2',
        batch_size=batch_size,
        shuffle=False,
        class_mode='categorical')

print("[INFO] evaluating network...")
test_generator.reset()
predIdxs = loaded_model.predict_generator(test_generator, steps=(test_generator.classes.size/batch_size))

# for each image in the testing set we need to find the index of the
# label with corresponding largest predicted probability
predIdxs = np.argmax(predIdxs, axis=1)

Found 1200 images belonging to 2 classes.
[INFO] evaluating network...


In [76]:
confusion_matrix(test_generator.classes, predIdxs)

array([[600,   0],
       [286, 314]])

In [77]:
accuracy_score(test_generator.classes, predIdxs)

0.7616666666666667

In [1]:
0.998326-0.998264

6.20000000000065e-05